### ISSUE TITLE
Autocomplete is only intermittently working

### ISSUE THREAD

**Issue by bjhecht** [cheetah90/wikibrain#7]
Seems to work sometimes, not other times.

**Comment by cheetah90** [comment]
@bjhecht 
Figured out the problem -Atlasify is using an English Wikipedia app on Microsoft Azure to do the autocomplete.  https://azuremarketplace.microsoft.com/en-us/marketplace/apps/aad.wikipediaenglish?tab=Overview. All of a sudden it started to return 403 error and that's why we saw errors today. I am not familiar with this English Wikipedia app on Azure. Is it just a replica of the autocomplete function on Wikipedia's searchbox? If yes, could we use the opensearch api from Wikipedia instead? https://en.wikipedia.org/w/api.php?action=help&modules=opensearch

**Comment by bjhecht** [comment]
No idea about that. Sounds good to switch.

**Comment by cheetah90** [comment]
The autocomplete on spatialization is working because it's using the wikipedia autocomplete. Atlasify should use that as well.

**Comment by bjhecht** [comment]
Huzzah!

**Comment by cheetah90** [comment]
Switched to use the Wikipedia API. Issue fixed.
